tutureproject/cli

.editorconfig, .gitignore, renderer/src/App.js, renderer/src/components/Content.js, renderer/src/util/content.json
1. add a new .editorconfig
2. checkout to development branch
3. update .editorconfig content
closes #4
=> Add .editorconfig 

.eslintignore, .eslintrc.js, .travis.yml, index.js, package-lock.json, package.json, utils.js
ESLint is essential for building maintainable codebase.  When ready to publish your changes, make sure to run `npm run lint` to see if you can pass ESLint checks. Currently `renderer` hasn't been modified to pass ESLint, so it's OK we won't pass Travis CI.
=> Integrate ESLint

index.js, utils.js
=> cli: append gitignore rules automatically

renderer/src/components/Catalog.js, renderer/src/components/Content.js
=> renderer: Add Affix on Catalog and scroll on Catalog and Content

renderer/src/App.js
=> renderer: Fix syncing with tuture.yml

index.js
=> cli: Add -y option in init command

README.md, README.zh-CN.md
* Clearer structure
* Add installation from npm registry
* Add `How to write a Tuture tutorial`
* Add travis build badge
=> docs: Add bilingual docs

package.json, renderer/src/App.css, renderer/src/App.js, renderer/src/components/Catalog.js, renderer/src/components/Content.js, renderer/src/components/ContentItem.js, renderer/src/components/css/Catalog.css, renderer/src/components/css/Content.css
Close #21 
Add a `Button` for switch diff viewType: `'split' | 'unified'`
Set default viewType to `'unified'`
=> renderer: Enable switching diff views

index.js, utils.js
Resolves #29.
Besides I have done some refactoring -- moving prompting and logging from `index.js` to `utils.js`.
=> cli: Implement destroy sub-command

utils.js
=> cli: Detect whether cwd is a valid git repo

utils.js
=> cli: Reject `tuture up` without init

index.js, utils.js
=> cli: Handle unknown command

renderer/src/App.css, renderer/src/components/ContentItem.js, renderer/src/components/css/ContentItem.css
=> renderer: collapsed generated files

.stylelintrc, .travis.yml, package-lock.json, package.json
=> lint: Add stylelint

.stylelintrc, renderer/package-lock.json, renderer/package.json, renderer/src/App.css, renderer/src/App.js, renderer/src/components/css/Change.css, renderer/src/components/css/Content.css, renderer/src/components/css/Diff.css, renderer/src/components/css/Hunk.css
=> renderer: change page title to tutorial name

renderer/src/App.js, renderer/src/components/ContentItem.js
=> renderer: enhance code style

utils/init.js
If .tuture is already ignored, do nothing.
=> cli: make `appendGitignore` idempotent

package.json
Currently there are some places not so good in **package.json**.
* Fix `main` field
* Use shorthand in `pretest` script
* Fix `repository` field
* Add `files` field
=> Minor tweaks to package.json

package.json, utils/git.js, utils/index.js, utils/init.js, utils/up.js, yarn.lock
Closes #59. Remove simple-git, use synchronous subprocesses instead.
=> Refactor git handlers

.npmrc, jest.config.js, package.json
And add **.npmrc** to disable package-lock.
=> Move jest config into package.json

README.md, appveyor.yml, tests/reload.test.js, tests/utils.js
Enable Continuous Integration on Windows platform.
=> Add Appveyor Integration

docs/TUTURE_YML_SPEC.md, docs/TUTURE_YML_SPEC.zh-CN.md
Add `intro` field to `diff` for displaying introduction before diff code.
=> docs: Add intro field to tuture.yml

bin/tuture, lib/common.js, lib/git.js, lib/tuture.js, lib/utils.js, tests/init.test.js, tests/reload.test.js, tests/tuture.test.js, tests/up.test.js, tests/utils.js
- Disable generation of default `explain` field (following the golden rule of **Don't make decisions for users**)
- Clear unused imports in test files
- Keep tuture bin minimal
=> Little refinements

lib/git.js, package.json, yarn.lock
=> cli: Re-implement git runner with Promise and Node API

README.md, README.zh-CN.md
User interviews reveal that we need some troubleshooting in installation section of README.
=> Add troubleshooting on installation

appveyor.yml, lib/tuture.js, lib/utils.js, package.json, yarn.lock
=> Fire tuture-server in up command

package.json, src/base.ts, src/commands/destroy.ts, src/commands/init.ts, src/commands/reload.ts, src/commands/up.ts, src/config.ts, src/types.ts, src/utils/git.ts, src/utils/index.ts, test/destroy.test.ts, test/init.test.ts, test/reload.test.ts, test/up.test.ts, test/utils.ts, tsconfig.json, yarn.lock
For those files that are not ignored, specify `display: true`.
=> Add display field

.prettierrc.js, package.json, src/commands/init.ts, src/commands/login.ts, src/commands/publish.ts, src/config.ts, src/types.ts, src/utils/git.ts, src/utils/index.ts, test/init.test.ts, tslint.json, yarn.lock
Implement `login` and `publish` command.
=> Implement api commands

README.md, src/commands/up.ts
You can now specify which port to use by offering `-p, --port` option in `up` command.
=> Add port option
